//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabySleep.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabySleep.Resources.Resx.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro users.
        /// </summary>
        public static string BsProUsers1 {
            get {
                return ResourceManager.GetString("BsProUsers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could use website version and share account with other persons.
        /// </summary>
        public static string BsProUsers2 {
            get {
                return ResourceManager.GetString("BsProUsers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several children.
        /// </summary>
        public static string BsSeveralChildren1 {
            get {
                return ResourceManager.GetString("BsSeveralChildren1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could be tracked.
        /// </summary>
        public static string BsSeveralChildren2 {
            get {
                return ResourceManager.GetString("BsSeveralChildren2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track information.
        /// </summary>
        public static string BsTrack1 {
            get {
                return ResourceManager.GetString("BsTrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about child sleeps: duration, quality, conditions, patterns.
        /// </summary>
        public static string BsTrack2 {
            get {
                return ResourceManager.GetString("BsTrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby sleep trainer for getting better child sleep.
        /// </summary>
        public static string BsTrainer {
            get {
                return ResourceManager.GetString("BsTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use charts.
        /// </summary>
        public static string BsUseCharts1 {
            get {
                return ResourceManager.GetString("BsUseCharts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for analyzing sleep information.
        /// </summary>
        public static string BsUseCharts2 {
            get {
                return ResourceManager.GetString("BsUseCharts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the app.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
    }
}
