//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabySleep.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivacyPolicyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabySleep.Resources.Resx.PrivacyPolicyResources", typeof(PrivacyPolicyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to this Privacy Policy.
        /// </summary>
        public static string ChangesH {
            get {
                return ResourceManager.GetString("ChangesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We reserve the right to change this Privacy Policy from time to time without notification. Such changes will be effective when posted on our website. By continuing to use the BabySleepApp or visit our website after we post such changes, you accept the Private Policy as modified..
        /// </summary>
        public static string ChangesP1 {
            get {
                return ResourceManager.GetString("ChangesP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of your personal information.
        /// </summary>
        public static string CollectionH {
            get {
                return ResourceManager.GetString("CollectionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We only collect personal information by lawful and fair means.  We collect personal information directly from Pro users..
        /// </summary>
        public static string CollectionP1 {
            get {
                return ResourceManager.GetString("CollectionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personally identifiable information may include, but is not limited to, your email address, your baby’s name, baby’s date of birth, etc. Once your account exists, you have the ability to review, update, and correct your personal information, in the event it changes..
        /// </summary>
        public static string CollectionP2 {
            get {
                return ResourceManager.GetString("CollectionP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you contact us through Contact, we may keep a record of your contact information and correspondence, and may use you email address, and any information that you provide to us in your message, to respond to you..
        /// </summary>
        public static string CollectionP3 {
            get {
                return ResourceManager.GetString("CollectionP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not sell, transfer, or disclose your personal information to any third parties other than for the limited purposes described in this policy..
        /// </summary>
        public static string CollectionP4 {
            get {
                return ResourceManager.GetString("CollectionP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string CookiesH {
            get {
                return ResourceManager.GetString("CookiesH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We store cookies (small text files managed by your web browser) on your computer in order to improve your experience with BabySleep website for Pro users. For example, we use cookies for authorization..
        /// </summary>
        public static string CookiesP1 {
            get {
                return ResourceManager.GetString("CookiesP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may refuse to accept cookies by changing the settings on your device. However, if you refuse it you may be unable to access certain parts of BabySleep website..
        /// </summary>
        public static string CookiesP2 {
            get {
                return ResourceManager.GetString("CookiesP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy policy describes how we collects and processes information that you may provide by using the BabySleepApp or by visiting our website at www.babysleepapp.com. Therefore, you should read it carefully before using any of our services..
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and complaints.
        /// </summary>
        public static string QuestionsH {
            get {
                return ResourceManager.GetString("QuestionsH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe that any of your rights with respect to your or others’ identifiable information have been violated by us, please contact us using email described in Contact page.
        /// </summary>
        public static string QuestionsP1 {
            get {
                return ResourceManager.GetString("QuestionsP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityH {
            get {
                return ResourceManager.GetString("SecurityH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hold your personal information in a secure cloud server..
        /// </summary>
        public static string SecurityP1 {
            get {
                return ResourceManager.GetString("SecurityP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We take all measures reasonably necessary to protect against the unauthorized access, use, alteration, or destruction of potentially personally-identifying information..
        /// </summary>
        public static string SecurityP2 {
            get {
                return ResourceManager.GetString("SecurityP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should keep in mind that no internet transmission is ever completely secure or error-free. In the event you send us an email, please remember that the email is not necessarily secured against interception by another party..
        /// </summary>
        public static string SecurityP3 {
            get {
                return ResourceManager.GetString("SecurityP3", resourceCulture);
            }
        }
    }
}
