//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabySleep.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChildSleepResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChildSleepResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabySleep.Resx.ChildSleepResources", typeof(ChildSleepResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Sleep.
        /// </summary>
        public static string AddSleep {
            get {
                return ResourceManager.GetString("AddSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awakenings.
        /// </summary>
        public static string Awakenings {
            get {
                return ResourceManager.GetString("Awakenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter awakenings.
        /// </summary>
        public static string AwakeningsPlaceholder {
            get {
                return ResourceManager.GetString("AwakeningsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby stroller.
        /// </summary>
        public static string BabyStroller {
            get {
                return ResourceManager.GetString("BabyStroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crib.
        /// </summary>
        public static string Crib {
            get {
                return ResourceManager.GetString("Crib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this sleep?.
        /// </summary>
        public static string DeleteSleepQuestion {
            get {
                return ResourceManager.GetString("DeleteSleepQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sleep.
        /// </summary>
        public static string DeleteSleepTitle {
            get {
                return ResourceManager.GetString("DeleteSleepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall asleep(min).
        /// </summary>
        public static string FallAsleep {
            get {
                return ResourceManager.GetString("FallAsleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter fall asleep time.
        /// </summary>
        public static string FallAsleepPlaceholder {
            get {
                return ResourceManager.GetString("FallAsleepPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedings.
        /// </summary>
        public static string Feedings {
            get {
                return ResourceManager.GetString("Feedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter feedings.
        /// </summary>
        public static string FeedingsPlaceholder {
            get {
                return ResourceManager.GetString("FeedingsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep in this time frame already exists.
        /// </summary>
        public static string SleepAlreadyExistsException {
            get {
                return ResourceManager.GetString("SleepAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep should last less than {0} hours.
        /// </summary>
        public static string SleepDurationException {
            get {
                return ResourceManager.GetString("SleepDurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string SleepMain {
            get {
                return ResourceManager.GetString("SleepMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep place.
        /// </summary>
        public static string SleepPlace {
            get {
                return ResourceManager.GetString("SleepPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep quality.
        /// </summary>
        public static string SleepQuality {
            get {
                return ResourceManager.GetString("SleepQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakefulness: .
        /// </summary>
        public static string Wakefulness {
            get {
                return ResourceManager.GetString("Wakefulness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woke.
        /// </summary>
        public static string Woke {
            get {
                return ResourceManager.GetString("Woke", resourceCulture);
            }
        }
    }
}
