// <auto-generated />
using System;
using BabySleep.EfData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BabySleep.EfData.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BabySleep.EfData.Models.Child", b =>
                {
                    b.Property<Guid>("ChildGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ChildGUID");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<short?>("BirthWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("BLOB");

                    b.HasKey("ChildGuid");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("BabySleep.EfData.Models.Setting", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RowID");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<short>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("RowId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BabySleep.EfData.Models.Sleep", b =>
                {
                    b.Property<Guid>("SleepGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SleepGuid");

                    b.Property<Guid>("ChildGuid")
                        .HasColumnType("TEXT");

                    b.Property<short>("AwakeningCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("date");

                    b.Property<short>("FallAsleepTime")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FeedingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<short>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SleepPlace")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("date");

                    b.HasKey("SleepGuid");

                    b.ToTable("Sleep");
                });
#pragma warning restore 612, 618
        }
    }
}
